using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static eTactWeb.DOM.Models.Common;

namespace eTactWeb.DOM.Models
{
    public class Features_OptionsModel:TimeStamp
    {
        public string FlagSelectUpdate { get; set; }
        public string Module { get; set; }
    
       
        public string Po_File_Name { get; set; }
        public string SaleInvoiceFileName { get; set; }
		[NotMapped]
		public bool DuplicateItemNameBool
		{
			get => DuplicateItemName == "Y";
			set => DuplicateItemName = value ? "Y" : "N";
		}
		public string DuplicateItemName { get; set; }
		[NotMapped]
		public bool PONOYearlyRenewBool
		{
			get => PONOYearlyRenew == "Y";
			set => PONOYearlyRenew = value ? "Y" : "N";
		}
		public string PONOYearlyRenew { get; set; }

		[NotMapped]
		public bool AutoGen_PartCodeBool
		{
			get => AutoGen_PartCode == "Y";
			set => AutoGen_PartCode = value ? "Y" : "N";
		}
		public string AutoGen_PartCode { get; set; }

		[NotMapped] 
		public bool AutoGeneratedPUrchaseOrderBool
		{
			get => AutoGeneratedPUrchaseOrder == "Y";
			set => AutoGeneratedPUrchaseOrder = value ? "Y" : "N";
		}
        public string AutoGeneratedPUrchaseOrder { get; set; }
		[NotMapped] 
		public bool AutoGenItemGroupCodeBool
		{
			get => AutoGenItemGroupCode == "Y";
			set => AutoGenItemGroupCode = value ? "Y" : "N";
		}

		public string AutoGenItemGroupCode { get; set; }
	[NotMapped] 
		public bool IsStoreMandatoryInItemMasterBool
		{
			get => IsStoreMandatoryInItemMaster == "Y";
			set => IsStoreMandatoryInItemMaster = value ? "Y" : "N";
		}

		public string IsStoreMandatoryInItemMaster { get; set; }
	
		[NotMapped] 
		public bool PONOEditableBool
		{
			get => PONOEditable == "Y";
			set => PONOEditable = value ? "Y" : "N";
		}

		public string PONOEditable { get; set; }

		[NotMapped] 
		public bool Allow_PO_PrintBool
		{
			get => Allow_PO_Print == "Y";
			set => Allow_PO_Print = value ? "Y" : "N";
		}

		public string Allow_PO_Print { get; set; }
		[NotMapped] 
		public bool AllowedToDispatchQtyMoreThenCloseSOPendQtyBool
        {
			get => AllowedToDispatchQtyMoreThenCloseSOPendQty == "Y";
			set => AllowedToDispatchQtyMoreThenCloseSOPendQty = value ? "Y" : "N";
		}

		public string AllowedToDispatchQtyMoreThenCloseSOPendQty { get; set; }

		[NotMapped] 
		public bool blockGateEntry4UnAppPOAmmBool
		{
			get => blockGateEntry4UnAppPOAmm == "Y";
			set => blockGateEntry4UnAppPOAmm = value ? "Y" : "N";
		}

		public string blockGateEntry4UnAppPOAmm { get; set; }
        public string ShowRateINGAteMrn { get; set; }
        public string CCMandatoryInQuery { get; set; }
        public string AllowBackdateReqWOBOM { get; set; }
        public long MaxDurationForReqToBePend { get; set; }
		[NotMapped]
		public bool AllowBackDateMRNEntryBool
		{
			get => AllowBackDateMRNEntry == "Y";
			set => AllowBackDateMRNEntry = value ? "Y" : "N";
		}
		public string AllowBackDateMRNEntry { get; set; }
		[NotMapped]
		public bool AllowToChangeBranchBool
		{
			get => AllowToChangeBranch == "Y";
			set => AllowToChangeBranch = value ? "Y" : "N";
		}
		public string AllowToChangeBranch { get; set; }
		public string allowforRecUnitgateentry { get; set; }

		[NotMapped]
		public bool AllowBackDateGAteEntryBool
		{
			get => AllowBackDateGAteEntry == "Y";
			set => AllowBackDateGAteEntry = value ? "Y" : "N";
		}
		public string AllowBackDateGAteEntry { get; set; }
		[NotMapped]
		public bool AllowGateRateEnabledBool
		{
			get => AllowGateRateEnabled == "Y";
			set => AllowGateRateEnabled = value ? "Y" : "N";
		}
		public string AllowGateRateEnabled { get; set; }

		[NotMapped]
		public bool BatchWiseInventoryBool
        {
			get => BatchWiseInventory == "Y";
			set => BatchWiseInventory = value ? "Y" : "N";
		}
		public string BatchWiseInventory { get; set; }

		[NotMapped]
		public bool AllowMultipleBuyerInSaleOrderBool
		{
			get => AllowMultipleBuyerInSaleOrder == "Y";
			set => AllowMultipleBuyerInSaleOrder = value ? "Y" : "N";
		}

		public string AllowMultipleBuyerInSaleOrder { get; set; }
		[NotMapped]
		public bool ShowHideSaleOrderEntryDetailBool
        {
			get => ShowHideSaleOrderEntryDetail == "Y";
			set => ShowHideSaleOrderEntryDetail = value ? "Y" : "N";
		}

		public string ShowHideSaleOrderEntryDetail { get; set; }
		[NotMapped]
		public bool ShowHideSaleOrderOtherRequiredDetailBool
		{
			get => ShowHideSaleOrderOtherRequiredDetail == "Y";
			set => ShowHideSaleOrderOtherRequiredDetail = value ? "Y" : "N";
		}

		public string ShowHideSaleOrderOtherRequiredDetail { get; set; }
		[NotMapped]
		public bool ShowHideSaleOrderConsigneeBool
		{
			get => ShowHideSaleOrderConsignee == "Y";
			set => ShowHideSaleOrderConsignee = value ? "Y" : "N";
		}

		public string ShowHideSaleOrderConsignee { get; set; }
		[NotMapped]
		public bool HideOtherFieldOFSaleOrderDetailTableBool
		{
			get => HideOtherFieldOFSaleOrderDetailTable == "Y";
			set => HideOtherFieldOFSaleOrderDetailTable = value ? "Y" : "N";
		}

		public string HideOtherFieldOFSaleOrderDetailTable { get; set; }


		[NotMapped]
		public bool EditableRateAndDiscountONSaleInvoiceBool
		{
			get => EditableRateAndDiscountONSaleInvoice == "Y";
			set => EditableRateAndDiscountONSaleInvoice = value ? "Y" : "N";
		}

		public string EditableRateAndDiscountONSaleInvoice { get; set; }
		[NotMapped]
		public bool ApproveSOForGenerateSaleInvoiceOrNotBool
		{
			get => ApproveSOForGenerateSaleInvoiceOrNot == "Y";
			set => ApproveSOForGenerateSaleInvoiceOrNot = value ? "Y" : "N";
		}

		public string ApproveSOForGenerateSaleInvoiceOrNot { get; set; }

		[NotMapped]
		public bool ShowHideEntryDetailBool
		{
			get => ShowHideEntryDetail == "Y";
			set => ShowHideEntryDetail = value ? "Y" : "N";
		}
		public string ShowHideEntryDetail { get; set; }

		[NotMapped]
		public bool ShowHideCustomerDetailBool
		{
			get => ShowHideCustomerDetail == "Y";
			set => ShowHideCustomerDetail = value ? "Y" : "N";
		}
		public string ShowHideCustomerDetail { get; set; }

		[NotMapped]
		public bool ShowHideOtherRequiredDetailBool
		{
			get => ShowHideOtherRequiredDetail == "Y";
			set => ShowHideOtherRequiredDetail = value ? "Y" : "N";
		}
		public string ShowHideOtherRequiredDetail { get; set; }

		[NotMapped]
		public bool ShowHideCurrencyBool
		{
			get => ShowHideCurrency == "Y";
			set => ShowHideCurrency = value ? "Y" : "N";
		}
		public string ShowHideCurrency { get; set; }

		[NotMapped]
		public bool ShowHideConsigneeBool
		{
			get => ShowHideConsignee == "Y";
			set => ShowHideConsignee = value ? "Y" : "N";
		}
		public string ShowHideConsignee { get; set; }

		[NotMapped]
		public bool ShowHideScheduleDetailBool
		{
			get => ShowHideScheduleDetail == "Y";
			set => ShowHideScheduleDetail = value ? "Y" : "N";
		}
		public string ShowHideScheduleDetail { get; set; }

		[NotMapped]
		public bool AllowToChangeStoreNameBool
		{
			get => AllowToChangeStoreName == "Y";
			set => AllowToChangeStoreName = value ? "Y" : "N";
		}
		public string AllowToChangeStoreName { get; set; }
		[NotMapped]
		public bool ShowHideOtherDetailsBool
		{
			get => ShowHideOtherDetails == "Y";
			set => ShowHideOtherDetails = value ? "Y" : "N";
		}
		public string ShowHideOtherDetails { get; set; }
		[NotMapped]
		public bool HideShowOtherDiscountBool
		{
			get => HideShowOtherDiscount == "Y";
			set => HideShowOtherDiscount = value ? "Y" : "N";
		}
		public string HideShowOtherDiscount { get; set; }

		[NotMapped]
		public bool HideOtherFieldOFDetailTableBool
		{
			get => HideOtherFieldOFDetailTable == "Y";
			set => HideOtherFieldOFDetailTable = value ? "Y" : "N";
		}
		public string HideOtherFieldOFDetailTable { get; set; }


		public string AllowToChangeStoreInMRN { get; set; }
        public string ItemPartcodeGenerationFormat { get; set; }
        public string AllowBackDateStockAdjustment { get; set; }
        public string AllowBAtchEditable { get; set; }
        public string AllowBAtchEditablePAssword { get; set; }
        public string AllowBackdateIssueWOBOM { get; set; }
        public string PurchaseOrderReport { get; set; }
        public string IssueWithScanner { get; set; }
        public string PurchaseorderPrintReportName { get; set; }
        public string PurchaseorderAmendPrintReportName { get; set; }
        public string PurchasSchedulePrintReportName { get; set; }
        public string PurchasScheduleAmendPrintReportName { get; set; }
        public string GateEntryPrintReportName { get; set; }
        public string MRNPrintReportName { get; set; }
        public string TakeSuuplierBatchOrSystmGeneratedBatchForInv { get; set; }
        public string RGPChallanPrintReportName { get; set; }
        public string NRGPChallanPrintReportName { get; set; }
        public string VendJWIssuePrintReportName { get; set; }
        public string VendJWRecPrintReportName { get; set; }
        public string CustJWIssuePrintReportName { get; set; }
        public string CUSTJWRecPrintReportName { get; set; }
        public string SaleorderPrintReportName { get; set; }
        public string SaleAmendPrintReportName { get; set; }
        public string SaleSchedulePrintReportName { get; set; }
        public string SaleScheduleAmendPrintReportName { get; set; }
        public string SaleBillPrintReportName { get; set; }
        public string JWSaleBillPrintReportName { get; set; }
        public string PurchaseRejPrintReportName { get; set; }
        public string DebitNotePrintReportName { get; set; }
        public string CreditNotePrintReportName { get; set; }
        public string SaleRejectionPrintReportName { get; set; }
        public string PurchaseBillPrintReportName { get; set; }
        public string DirectPurchaseBillPrintReportName { get; set; }
        public string PurchBillVoucherPrintReportName { get; set; }
        public string DirectPurchBillVoucherPrintReportName { get; set; }
        public string BankRecVoucherPrintReportName { get; set; }
        public string BankPaymentVoucherPrintReportName { get; set; }
        public string CashRecVoucherPrintReportName { get; set; }
        public string CashPaymentVoucherPrintReportName { get; set; }
        public string JournalVoucherPrintReportName { get; set; }
        public string AllowBackDateRequsitionWITHBOM { get; set; }
        public string AllowBackDateISSUEWITHBOM { get; set; }
        public string AllowBackDatePURCHASEORDER { get; set; }
        public string AllowBackDateINDENT { get; set; }
        public string AllowBackDateMRIR { get; set; }
        
        public string ALLOWBACKDATRECCHALLAN { get; set; }
        public string AllowBackDateJOBWorkIssue { get; set; }
        public string ALLOWBACKDATEJobworkRec { get; set; }
        public string AllowBackDateRECEIVEINSTORE { get; set; }
		[NotMapped]
		public bool AllowBackDateSALEBILLBool
		{
			get => AllowBackDateSALEBILL == "Y";
			set => AllowBackDateSALEBILL = value ? "Y" : "N";
		}

		public string AllowBackDateSALEBILL { get; set; }

		[NotMapped]
		public bool AccSaleBillManualTaxAlloweedBool
		{
			get => AccSaleBillManualTaxAlloweed == "Y";
			set => AccSaleBillManualTaxAlloweed = value ? "Y" : "N";
		}

		public string AccSaleBillManualTaxAlloweed { get; set; }

		[NotMapped]
		public bool salebillShowItemBatchFIFOBasedBool
		{
			get => salebillShowItemBatchFIFOBased == "Y";
			set => salebillShowItemBatchFIFOBased = value ? "Y" : "N";
		}

		public string salebillShowItemBatchFIFOBased { get; set; }

		// Allow Prod WithoutBom
		[NotMapped]
		public bool AllowProdWithoutBomBool
		{
			get => AllowProdWithoutBom == "Y";
			set => AllowProdWithoutBom = value ? "Y" : "N";
		}
		public string AllowProdWithoutBom { get; set; }

		// ProdSch Allow To Add Manual NewItem
		[NotMapped]
		public bool ProdSchAllowToAddManualNewItemBool
		{
			get => ProdSchAllowToAddManualNewItem == "Y";
			set => ProdSchAllowToAddManualNewItem = value ? "Y" : "N";
		}
		public string ProdSchAllowToAddManualNewItem { get; set; }

		// Prod Entry Allow To Add RMItem
		[NotMapped]
		public bool ProdEntryAllowToAddRMItemBool
		{
			get => ProdEntryAllowToAddRMItem == "Y";
			set => ProdEntryAllowToAddRMItem = value ? "Y" : "N";
		}
		public string ProdEntryAllowToAddRMItem { get; set; }

		// Prod Entry Allow To Add WithoutRM
		[NotMapped]
		public bool ProdEntryAllowToAddWithoutRMBool
		{
			get => ProdEntryAllowToAddWithoutRM == "Y";
			set => ProdEntryAllowToAddWithoutRM = value ? "Y" : "N";
		}
		public string ProdEntryAllowToAddWithoutRM { get; set; }

		// Prod Entry Allow To Add NegativeStock
		[NotMapped]
		public bool ProdEntryAllowToAddNegativeStockBool
		{
			get => ProdEntryAllowToAddNegativeStock == "Y";
			set => ProdEntryAllowToAddNegativeStock = value ? "Y" : "N";
		}
		public string ProdEntryAllowToAddNegativeStock { get; set; }

		// BatchWise Production
		[NotMapped]
		public bool BatchWiseProductionBool
		{
			get => BatchWiseProduction == "Y";
			set => BatchWiseProduction = value ? "Y" : "N";
		}
		public string BatchWiseProduction { get; set; }

		// Prod Entry Allow BackDate
		[NotMapped]
		public bool ProdEntryAllowBackDateBool
		{
			get => ProdEntryAllowBackDate == "Y";
			set => ProdEntryAllowBackDate = value ? "Y" : "N";
		}
		public string ProdEntryAllowBackDate { get; set; }

		// Allow BackDate Daily Production
		[NotMapped]
		public bool AllowBackDateDAILYPRODUCTIONBool
		{
			get => AllowBackDateDAILYPRODUCTION == "Y";
			set => AllowBackDateDAILYPRODUCTION = value ? "Y" : "N";
		}
		public string AllowBackDateDAILYPRODUCTION { get; set; }
		[NotMapped]
		public bool CheckPOPendFromPOonlyNotFromAmendmentBool
		{
			get => CheckPOPendFromPOonlyNotFromAmendment == "Y";
			set => CheckPOPendFromPOonlyNotFromAmendment = value ? "Y" : "N";
		}
		public string CheckPOPendFromPOonlyNotFromAmendment { get; set; }

		public string AllowBackDateTRANSFERMATERIAL { get; set; }
        
        public string AllowBackDateReceiveChallanEntry { get; set; }
       
        public string FIFOBasedBatchInventoryInJobWorkIss { get; set; }
        public string AllowBackDateCustomerJWIssue { get; set; }
        public string IssueViaScanningBarcode { get; set; }
        public string AllowBackDateWorkorderEntry { get; set; }
        public string AllowBackDateInterStoreTransfer { get; set; }
        public string VendorJWAdjustAutoOrManual { get; set; }
        public string AllowBackDateProductionScheduleEntry { get; set; }
        public string InProdScheduleShowSumOrDetail { get; set; }
        public string PrdProdEntryAgainstWOProdSchReqManual { get; set; }
        
        public string VoucherRotationDailyMonthYearly { get; set; }
      
        public string AccAllowtochangeDocumentinPurchaseBill { get; set; }
        public string AccPasswordToChangeDocumentinPurchaseBill { get; set; }
        public long ProdMaxNoofIteminWorkorder { get; set; }
        public string AccPasswordToAllowManualTax { get; set; }
		[NotMapped]
		public bool AccSaleBillManualTaxAllowedBool
		{
			get => AccSaleBillManualTaxAllowed == "Y";
			set => AccSaleBillManualTaxAllowed = value ? "Y" : "N";
		}
		public string AccSaleBillManualTaxAllowed { get; set; }
		[NotMapped]
		public bool AccAllowtochangeDocumnetinPurchaseBillBool
		{
			get => AccAllowtochangeDocumnetinPurchaseBill == "Y";
			set => AccAllowtochangeDocumnetinPurchaseBill = value ? "Y" : "N";
		}
		public string AccAllowtochangeDocumnetinPurchaseBill { get; set; }
		[NotMapped]
		public bool AccAllowTochangeVoucherDateInPurchBillBool
		{
			get => AccAllowTochangeVoucherDateInPurchBill == "Y";
			set => AccAllowTochangeVoucherDateInPurchBill = value ? "Y" : "N";
		}
		public string AccAllowTochangeVoucherDateInPurchBill { get; set; }
		[NotMapped]
		public bool AccAllowtochangeInvoiceNoDateinPurchaseBillBool
		{
			get => AccAllowtochangeInvoiceNoDateinPurchaseBill == "Y";
			set => AccAllowtochangeInvoiceNoDateinPurchaseBill = value ? "Y" : "N";
		}
		public string AccAllowtochangeInvoiceNoDateinPurchaseBill { get; set; }
		[NotMapped]
		public bool PoallowtoprintWithoutApprovalBool
		{
			get => PoallowtoprintWithoutApproval == "Y";
			set => PoallowtoprintWithoutApproval = value ? "Y" : "N";
		}
		public string PoallowtoprintWithoutApproval { get; set; }
		[NotMapped]
		public bool POClosePOAlwaysAgainstIndentBool
		{
			get => POClosePOAlwaysAgainstIndent == "Y";
			set => POClosePOAlwaysAgainstIndent = value ? "Y" : "N";
		}
		public string POClosePOAlwaysAgainstIndent { get; set; }
		[NotMapped]
		public bool allowtostartdateindashboarddateBool
		{
			get => allowtostartdateindashboarddate == "Y";
			set => allowtostartdateindashboarddate = value ? "Y" : "N";
		}
		public string allowtostartdateindashboarddate { get; set; }

		public string AccPurchaseVoucherPrintoutFileName { get; set; }
		public string AccPurchaseBillInvoicePrintoutFileName { get; set; }

        [NotMapped]
        public bool PONotAllowedWithoutPartCodePartyWiseDefinitionBool
        {
            get => PONotAllowedWithoutPartCodePartyWiseDefinition == "Y";
            set => PONotAllowedWithoutPartCodePartyWiseDefinition = value ? "Y" : "N";
        }
        public string PONotAllowedWithoutPartCodePartyWiseDefinition { get; set; }
       
        public string AccAllowBackdateVoucherEntry { get; set; }
        public string AccBackdateVoucherEntryPassword { get; set; }
        public string IndentReportName { get; set; }
        public string AccAllowToChangeVoucherDateInPurchBill { get; set; }
        public string ProdAllowMultiplePlanInProdSchOrNot { get; set; }
        public string AccPurchaseVoucherPrintoutFilename { get; set; }
        public string AccPurchaseBillInvoicePrintoutFilename { get; set; }
        
     
        public decimal PurchaseIncrementPercentageofRMInMRP { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string Searchbox { get; set; }
        public string Type { get; set; }


		public string AccPurchaseBillInvoicePrintoutfilename { get; set; }
		public string ShowHideDirectPurchaseBillEntryDetail { get; set; }
		[NotMapped]
		public bool ShowHideDirectPurchaseBillEntryDetailBool
		{
			get => ShowHideDirectPurchaseBillEntryDetail?.Trim() == "Y";
			set => ShowHideDirectPurchaseBillEntryDetail = value ? "Y" : "N";
		}

		public string ShowHideDirectPurchaseBillCustomerDetail { get; set; }
		[NotMapped]
		public bool ShowHideDirectPurchaseBillCustomerDetailBool
		{
			get => ShowHideDirectPurchaseBillCustomerDetail?.Trim() == "Y";
			set => ShowHideDirectPurchaseBillCustomerDetail = value ? "Y" : "N";
		}

		public string ShowHideDirectPurchaseBillOtherRequiredDetail { get; set; }
		[NotMapped]
		public bool ShowHideDirectPurchaseBillOtherRequiredDetailBool
		{
			get => ShowHideDirectPurchaseBillOtherRequiredDetail?.Trim() == "Y";
			set => ShowHideDirectPurchaseBillOtherRequiredDetail = value ? "Y" : "N";
		}

		public string ShowHideDirectPurchaseBillCurrency { get; set; }
		[NotMapped]
		public bool ShowHideDirectPurchaseBillCurrencyBool
		{
			get => ShowHideDirectPurchaseBillCurrency?.Trim() == "Y";
			set => ShowHideDirectPurchaseBillCurrency = value ? "Y" : "N";
		}

		public string ShowHideDirectPurchaseBillConsignee { get; set; }
		[NotMapped]
		public bool ShowHideDirectPurchaseBillConsigneeBool
		{
			get => ShowHideDirectPurchaseBillConsignee?.Trim() == "Y";
			set => ShowHideDirectPurchaseBillConsignee = value ? "Y" : "N";
		}

		public string ShowHideDirectPurchaseBillScheduleDetail { get; set; }
		[NotMapped]
		public bool ShowHideDirectPurchaseBillScheduleDetailBool
		{
			get => ShowHideDirectPurchaseBillScheduleDetail?.Trim() == "Y";
			set => ShowHideDirectPurchaseBillScheduleDetail = value ? "Y" : "N";
		}

		public string HideOtherFieldOFDirectPurchaseBillDetailTable { get; set; }
		[NotMapped]
		public bool HideOtherFieldOFDirectPurchaseBillDetailTableBool
		{
			get => HideOtherFieldOFDirectPurchaseBillDetailTable?.Trim() == "Y";
			set => HideOtherFieldOFDirectPurchaseBillDetailTable = value ? "Y" : "N";
		}

		public string ShowHideDirectPurchaseBillOtherDetails { get; set; }
		[NotMapped]
		public bool ShowHideDirectPurchaseBillOtherDetailsBool
		{
			get => ShowHideDirectPurchaseBillOtherDetails?.Trim() == "Y";
			set => ShowHideDirectPurchaseBillOtherDetails = value ? "Y" : "N";
		}

		public string ShowHidePurchaseBillEntryDetail { get; set; }
		[NotMapped]
		public bool ShowHidePurchaseBillEntryDetailBool
		{
			get => ShowHidePurchaseBillEntryDetail?.Trim() == "Y";
			set => ShowHidePurchaseBillEntryDetail = value ? "Y" : "N";
		}

		public string ShowHidePurchaseBillCustomerDetail { get; set; }
		[NotMapped]
		public bool ShowHidePurchaseBillCustomerDetailBool
		{
			get => ShowHidePurchaseBillCustomerDetail?.Trim() == "Y";
			set => ShowHidePurchaseBillCustomerDetail = value ? "Y" : "N";
		}

		public string ShowHidePurchaseBillOtherRequiredDetail { get; set; }
		[NotMapped]
		public bool ShowHidePurchaseBillOtherRequiredDetailBool
		{
			get => ShowHidePurchaseBillOtherRequiredDetail?.Trim() == "Y";
			set => ShowHidePurchaseBillOtherRequiredDetail = value ? "Y" : "N";
		}

		public string ShowHidePurchaseBillCurrency { get; set; }
		[NotMapped]
		public bool ShowHidePurchaseBillCurrencyBool
		{
			get => ShowHidePurchaseBillCurrency?.Trim() == "Y";
			set => ShowHidePurchaseBillCurrency = value ? "Y" : "N";
		}

		public string ShowHidePurchaseBillConsignee { get; set; }
		[NotMapped]
		public bool ShowHidePurchaseBillConsigneeBool
		{
			get => ShowHidePurchaseBillConsignee?.Trim() == "Y";
			set => ShowHidePurchaseBillConsignee = value ? "Y" : "N";
		}

		public string ShowHidePurchaseBillScheduleDetail { get; set; }
		[NotMapped]
		public bool ShowHidePurchaseBillScheduleDetailBool
		{
			get => ShowHidePurchaseBillScheduleDetail?.Trim() == "Y";
			set => ShowHidePurchaseBillScheduleDetail = value ? "Y" : "N";
		}

		public string HideOtherFieldOFPurchaseBillDetailTable { get; set; }
		[NotMapped]
		public bool HideOtherFieldOFPurchaseBillDetailTableBool
		{
			get => HideOtherFieldOFPurchaseBillDetailTable?.Trim() == "Y";
			set => HideOtherFieldOFPurchaseBillDetailTable = value ? "Y" : "N";
		}

		public string ShowHidePurchaseBillOtherDetails { get; set; }
		[NotMapped]
		public bool ShowHidePurchaseBillOtherDetailsBool
		{
			get => ShowHidePurchaseBillOtherDetails?.Trim() == "Y";
			set => ShowHidePurchaseBillOtherDetails = value ? "Y" : "N";
		}

		public string AddInventoryByDirectPurchaseBill { get; set; }
		[NotMapped]
		public bool AddInventoryByDirectPurchaseBillBool
		{
			get => AddInventoryByDirectPurchaseBill?.Trim() == "Y";
			set => AddInventoryByDirectPurchaseBill = value ? "Y" : "N";
		}
		
		[NotMapped]
		public bool FIFOBasedBatchInventoryBool
		{
			get => FIFOBasedBatchInventory?.Trim() == "Y";
			set => FIFOBasedBatchInventory = value ? "Y" : "N";
		}
		public string FIFOBasedBatchInventory { get; set; }

		[NotMapped]
		public bool AllowBackDateIssueChallanBool
		{
			get => AllowBackDateIssueChallan?.Trim() == "Y";
			set => AllowBackDateIssueChallan = value ? "Y" : "N";
		}
		public string AllowBackDateIssueChallan { get; set; }

		[NotMapped]
		public bool IssueChaallanTaxIsMandatoryBool
		{
			get => IssueChaallanTaxIsMandatory?.Trim() == "Y";
			set => IssueChaallanTaxIsMandatory = value ? "Y" : "N";
		}
		public string IssueChaallanTaxIsMandatory { get; set; }
		[NotMapped]
		public bool ShowHideOtherDetailTableDataBool
		{
			get => ShowHideOtherDetailTableData?.Trim() == "Y";
			set => ShowHideOtherDetailTableData = value ? "Y" : "N";
		}
		public string ShowHideOtherDetailTableData { get; set; }


		public IList<Features_OptionsModel> features_OptionsModelsGrid { get; set; }
    }
}
