using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static eTactWeb.DOM.Models.Common;

namespace eTactWeb.DOM.Models
{
    public class Features_OptionsModel:TimeStamp
    {
        public string FlagSelectUpdate { get; set; }
        public string Module { get; set; }
        public string AutoGen_PartCode { get; set; }
        public string DuplicateItemName { get; set; }
        public string Allow_PO_Print { get; set; }
        public string Po_File_Name { get; set; }
        public string SaleInvoiceFileName { get; set; }
        public string PONOEditable { get; set; }
        public string PONOYearlyRenew { get; set; }
        public string AutoGeneratedPUrchaseOrder { get; set; }
        public string AutoGenItemGroupCode { get; set; }
        public string BlockGateEntry4UnAppPOAmm { get; set; }
        public string ShowRateINGAteMrn { get; set; }
        public string CCMandatoryInQuery { get; set; }
        public string BatchWiseInventory { get; set; }
        public string AllowBackdateReqWOBOM { get; set; }
        public string AllowBackDateGAteEntry { get; set; }
        public string AllowToChangeBranch { get; set; }
        public long MaxDurationForReqToBePend { get; set; }
        public string AllowBackDateMRNEntry { get; set; }
        public string AllowMultipleBuyerInSaleOrder { get; set; }
        public string AllowToChangeStoreInMRN { get; set; }
        public string ItemPartcodeGenerationFormat { get; set; }
        public string AllowBackDateStockAdjustment { get; set; }
        public string AllowBAtchEditable { get; set; }
        public string AllowBAtchEditablePAssword { get; set; }
        public string AllowBackdateIssueWOBOM { get; set; }
        public string PurchaseOrderReport { get; set; }
        public string IssueWithScanner { get; set; }
        public string PurchaseorderPrintReportName { get; set; }
        public string PurchaseorderAmendPrintReportName { get; set; }
        public string PurchasSchedulePrintReportName { get; set; }
        public string PurchasScheduleAmendPrintReportName { get; set; }
        public string GateEntryPrintReportName { get; set; }
        public string MRNPrintReportName { get; set; }
        public string RGPChallanPrintReportName { get; set; }
        public string NRGPChallanPrintReportName { get; set; }
        public string VendJWIssuePrintReportName { get; set; }
        public string VendJWRecPrintReportName { get; set; }
        public string CustJWIssuePrintReportName { get; set; }
        public string CUSTJWRecPrintReportName { get; set; }
        public string SaleorderPrintReportName { get; set; }
        public string SaleAmendPrintReportName { get; set; }
        public string SaleSchedulePrintReportName { get; set; }
        public string SaleScheduleAmendPrintReportName { get; set; }
        public string SaleBillPrintReportName { get; set; }
        public string JWSaleBillPrintReportName { get; set; }
        public string PurchaseRejPrintReportName { get; set; }
        public string DebitNotePrintReportName { get; set; }
        public string CreditNotePrintReportName { get; set; }
        public string SaleRejectionPrintReportName { get; set; }
        public string PurchaseBillPrintReportName { get; set; }
        public string DirectPurchaseBillPrintReportName { get; set; }
        public string PurchBillVoucherPrintReportName { get; set; }
        public string DirectPurchBillVoucherPrintReportName { get; set; }
        public string BankRecVoucherPrintReportName { get; set; }
        public string BankPaymentVoucherPrintReportName { get; set; }
        public string CashRecVoucherPrintReportName { get; set; }
        public string CashPaymentVoucherPrintReportName { get; set; }
        public string JournalVoucherPrintReportName { get; set; }
        public string AllowBackDateRequsitionWITHBOM { get; set; }
        public string AllowBackDateISSUEWITHBOM { get; set; }
        public string AllowBackDatePURCHASEORDER { get; set; }
        public string AllowBackDateINDENT { get; set; }
        public string AllowBackDateMRIR { get; set; }
        public string AllowBackDateIssueChallan { get; set; }
        public string ALLOWBACKDATRECCHALLAN { get; set; }
        public string AllowBackDateJOBWorkIssue { get; set; }
        public string ALLOWBACKDATEJobworkRec { get; set; }
        public string AllowBackDateRECEIVEINSTORE { get; set; }
        public string AllowBackDateSALEBILL { get; set; }
        public string AllowBackDateDAILYPRODUCTION { get; set; }
        public string AllowBackDateTRANSFERMATERIAL { get; set; }
        public string CheckPOPendFromPOonlyNotFromAmendment { get; set; }
        public string AllowBackDateReceiveChallanEntry { get; set; }
        public string FIFOBasedBatchInventory { get; set; }
        public string FIFOBasedBatchInventoryInJobWorkIss { get; set; }
        public string AllowGateRateEnabled { get; set; }
        public string AllowBackDateCustomerJWIssue { get; set; }
        public string IssueViaScanningBarcode { get; set; }
        public string AllowBackDateWorkorderEntry { get; set; }
        public string AllowBackDateInterStoreTransfer { get; set; }
        public string VendorJWAdjustAutoOrManual { get; set; }
        public string AllowBackDateProductionScheduleEntry { get; set; }
        public string InProdScheduleShowSumOrDetail { get; set; }
        public string PrdProdEntryAgainstWOProdSchReqManual { get; set; }
        public string AllowProdWithoutBom { get; set; }
        public string ProdSchAllowToAddManualNewItem { get; set; }
        public string ProdEntryAllowToAddRMItem { get; set; }
        public string ProdEntryAllowToAddWithoutRM { get; set; }
        public string ProdEntryAllowToAddNegativeStock { get; set; }
        public string BatchWiseProduction { get; set; }
        public string VoucherRotationDailyMonthYearly { get; set; }
        public string ProdEntryAllowBackDate { get; set; }
        public string AccAllowtochangeDocumentinPurchaseBill { get; set; }
        public string AccPasswordToChangeDocumentinPurchaseBill { get; set; }
        public string AccAllowtochangeInvoiceNoDateinPurchaseBill { get; set; }
        public long ProdMaxNoofIteminWorkorder { get; set; }
        public string AccPasswordToAllowManualTax { get; set; }
        public string AccSaleBillManualTaxAllowed { get; set; }
        public string POClosePOAlwaysAgainstIndent { get; set; }
        public string AccAllowtochangeDocumnetinPurchaseBill { get; set; }
        public string AccAllowBackdateVoucherEntry { get; set; }
        public string AccBackdateVoucherEntryPassword { get; set; }
        public string IndentReportName { get; set; }
        public string AccAllowToChangeVoucherDateInPurchBill { get; set; }
        public string ProdAllowMultiplePlanInProdSchOrNot { get; set; }
        public string AccPurchaseVoucherPrintoutFilename { get; set; }
        public string AccPurchaseBillInvoicePrintoutFilename { get; set; }
        public string PoallowtoprintWithoutApproval { get; set; }
        public string IssueChaallanTaxIsMandatory { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string Searchbox { get; set; }
        public string Type { get; set; }
        public IList<Features_OptionsModel> features_OptionsModelsGrid { get; set; }
    }
}
