using eTactWeb.DOM.Models;
using Microsoft.AspNetCore.Mvc;
using static eTactWeb.DOM.Models.Common;
namespace eTactWeb.Services.Interface;

public interface IProductionEntry
{
    Task<ResponseResult> GetPoNumberDropDownList(string Flag, string Service, string SPName, string AccountCode, int Year, int DocTypeId);
    Task<ResponseResult> FillSaleBillChallan(int AccountCode, int doctype, int ItemCode);
    Task<ResponseResult> FillChallanQty(int AccountCode, int ItemCode, string ChallanNo);
    Task<ResponseResult> FillSaleBillQty(int AccountCode, int ItemCode, int SaleBillNo);
    Task<ResponseResult> GetPopUpData(string Flag, int AccountCode, string PONO);
    Task<ResponseResult> AltUnitConversion(int ItemCode, int AltQty, int UnitQty);
    Task<ResponseResult> GetScheDuleByYearCodeandAccountCode(string Flag, string AccountCode, string YearCode, string poNo);
    Task<ResponseResult> GetFeatureOption(string Flag, string SPName);
    Task<ResponseResult> SaveProductionEntry(ProductionEntryModel model, DataTable GIGrid, DataTable OperatorGrid, DataTable BreakDownGrid, DataTable ScrapGrid);
    Task<ProductionEntryDashboard> GetDashboardData(string FromDate, string ToDate, string SlipNo, string ItemName, string PartCode, string ProdPlanNo, string ProdSchNo, string ReqNo, string DashboardType);
    Task<ResponseResult> DeleteByID(int ID, int YC, string CC, string EntryByMachineName, string EntryDate, int ActualEntryBy);
    Task<ResponseResult> FillEntryandGate(string Flag, int YearCode, string SPName);
    Task<ResponseResult> FillShift();
    Task<ResponseResult> CheckAllowToAddNegativeStock();
    Task<ResponseResult> FillTool();
    Task<ResponseResult> FillShiftTime(int ShiftId);
    Task<ResponseResult> FillStore();
    Task<ResponseResult> FillWorkcenter();
    Task<ResponseResult> GetUnit(int RmItemCode);
    Task<ResponseResult> GetScrapUnit(int ScrapItemCode);
    Task<ResponseResult> GetWorkCenterTotalStock(string Flag, int ItemCode, int WcId, string TillDate);
    Task<ResponseResult> GetWorkCenterQty(string Flag, int ItemCode, int WcId, string TillDate, string BatchNo, string UniqueBatchNo);
    Task<ResponseResult> FillIssWorkcenter(string QcMandatory);
    Task<ResponseResult> CheckForEditandDelete(string ProdSlipNo,int YearCode);
    Task<ResponseResult> FillIssStore();
    Task<ResponseResult> FillOperation(int ItemCode, int WcId);
    Task<ResponseResult> FillMachineGroup();
    Task<ProductionEntryModel> GetChildData(string Flag, string SPName, int WcId, int YearCode, float ProdQty, int ItemCode, string ProdDate, int BomNo);
    Task<ResponseResult> GetItems(string ProdAgainst, int YearCode);
    Task<ResponseResult> GetPartCode(string ProdAgainst, int YearCode);
    Task<ResponseResult> FillMachineName();
    Task<ProductionEntryModel> FillScrapData(int FGItemCode, decimal FgProdQty, string BomNo);
    Task<ResponseResult> FillSuperwiser();
    Task<ResponseResult> FillOperator();
    Task<ResponseResult> FillOperatorName();
    Task<ResponseResult> FillBreakdownreason();
    Task<ResponseResult> FillResponsibleEmp();
    Task<ResponseResult> FillScrapItems();
    Task<ResponseResult> FillResFactor();
    Task<ResponseResult> FillScrapPartCode();
    Task<ResponseResult> FillScrapType();
    Task<ResponseResult> FillRMItemName();
    Task<ResponseResult> FillRMPartCode();
    Task<ResponseResult> FillAltItemName();
    Task<ResponseResult> FillAltPartCode();
    Task<ResponseResult> GetLastProddate(int YearCode);
    Task<ResponseResult> GetBatchNumber(string SPName, int ItemCode, int YearCode, float WcId, string TransDate, string BatchNo);
    Task<ResponseResult> DisplayBomDetail(int ItemCode, float WOQty, int BomRevNo);
    Task<ResponseResult> DisplayRoutingDetail(int ItemCode);
    Task<ResponseResult> FillReqNo(string FromDate, string Todate, string ProdAgainst, int ItemCode);
    Task<ResponseResult> FillProdSchNo(string FromDate, string Todate, string ProdAgainst, int ItemCode);
    Task<ResponseResult> FillBomNo(int ItemCode);
    Task<ResponseResult> GetProcessDetail(int ItemCode, int ProcessId, int WcId);
    Task<ResponseResult> FillReqYear(string FromDate, string Todate, string ProdAgainst, string ReqNo);
    Task<ResponseResult> FillReqDate(string FromDate, string Todate, string ProdAgainst, string ReqNo, int ReqYearCode, int ItemCode);
    Task<ResponseResult> FillProdDate(string FromDate, string ToDate, string ProdAgainst, string ProdSchNo, int ProdPlanYearCode);
    Task<ResponseResult> FillProdSchYear(string FromDate, string Todate, string ProdAgainst, string ProdSch);
    Task<ResponseResult> FillReqQty(string CurrentDate, string ProdAgainst, string ReqNo, int YearCode, int ItemCode, int ReqYearCode);
    Task<ResponseResult> FillPendQty(string CurrentDate, string ProdAgainst, string ProdSchNo, int YearCode, int ItemCode, int ProdSchYear,int Entryid);
    Task<ResponseResult> CheckEditOrDelete(string ProdSlipNo, int YearCode);
    Task<ResponseResult> GetDashboardData();
    Task<ResponseResult> FillIssWorkcenterForQcMandatory(string QcMandatory);
    Task<ProductionEntryDashboard> GetDashboardDetailData(string FromDate, string ToDate, string SlipNo, string ItemName, string PartCode, string ProdPlanNo, string ProdSchNo, string ReqNo, string DashboardType);
    Task<ProductionEntryDashboard> GetBatchwiseDetail(string FromDate, string ToDate, string SlipNo, string ItemName, string PartCode, string ProdPlanNo, string ProdSchNo, string ReqNo, string DashboardType);
    Task<ProductionEntryDashboard> GetBreakdownData(string FromDate, string ToDate);
    Task<ProductionEntryDashboard> GetOperationData(string FromDate, string ToDate);
    Task<ProductionEntryDashboard> GetScrapData(string FromDate, string ToDate);
    Task<ProductionEntryModel> GetViewByID(int ID, int YearCode);
    Task<ResponseResult> CheckFeatureOption();
    Task<ResponseResult> CCEnableDisable();
    Task<ResponseResult> GetFormRights(int uId);
    Task<ResponseResult> FillProdPlanDetail(string FromDate, string ToDate, string ProdAgainst, string ProdSchNo, int ProdYearCode);
    Task<ResponseResult> GetDateforBreakdown(string Flag, string DiffType, string QtyOfTime, string FromTime);
    Task<ResponseResult> GetTimeDiff(string Flag, string ToTime, string DiffType, string FromTime);
    Task<ResponseResult> CheckDuplicateEntry(int YearCode, int AccountCode, string InvNo, int DocType);

    public Task<PendingProductionEntryModel> GetPendingProductionEntry(int Yearcode);

}
