using eTactWeb.Data.Common;
using eTactWeb.DOM.Models;
using eTactWeb.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Newtonsoft.Json;
using static eTactWeb.Data.Common.CommonFunc;
using static eTactWeb.DOM.Models.Common;

namespace eTactWeb.Controllers
{
    public class Features_OptionsController : Controller
    {
        private readonly IDataLogic _IDataLogic;
        public IFeatures_Options _IFeatures_Options { get; }

        private readonly ILogger<Features_OptionsController> _logger;
        private readonly IConfiguration iconfiguration;
        private readonly IMemoryCache _MemoryCache;
        public IWebHostEnvironment _IWebHostEnvironment { get; }
        public Features_OptionsController(ILogger<Features_OptionsController> logger, IDataLogic iDataLogic, IFeatures_Options iFeatures_Options, IMemoryCache iMemoryCache, EncryptDecrypt encryptDecrypt, IWebHostEnvironment iWebHostEnvironment, IConfiguration iconfiguration)
        {
            _logger = logger;
            _IDataLogic = iDataLogic;
            _IFeatures_Options = iFeatures_Options;
            _MemoryCache = iMemoryCache;
            _IWebHostEnvironment = iWebHostEnvironment;
            this.iconfiguration = iconfiguration;
        }
        [Route("{controller}/Index")]
        [HttpGet]
        public async Task<ActionResult> Features_Options(int ID, string Mode, string Type, string AutoGen_PartCode,string DuplicateItemName,string ItemPartcodeGenerationFormat,
             string Po_File_Name, string PONOEditable, string PONOYearlyRenew, string AutoGeneratedPUrchaseOrder, string PurchaseOrderReport,
    string PurchaseorderPrintReportName, string PurchaseorderAmendPrintReportName, string PurchasSchedulePrintReportName,
    string PurchasScheduleAmendPrintReportName, string AllowBackDatePURCHASEORDER, string AllowBackDateINDENT,
    string CheckPOPendFromPOonlyNotFromAmendment,string SOFileName,string AutoGenItemGroupCode,string AllowMultipleBuyerInSO,string SOPrintReportName
            ,string SaleAmendPrintReportName,string SaleSchedulePrintReportName,string SaleScheduleAmendPrintReportName,
    string BlockGateEntry4UnAppPOAmm,string AllowBackDateGateEntry, string ShowRateInGateMRN,string GateEntryPrintReportName,
        string AllowGateRateEnabled, string AllowBackDateMRNEntry, string AllowToChangeStoreInMRN,string MRNPrintReportName,
        string AllowBackDateMRIR, string CCMandatoryInQuery,string BatchWiseInventory,string AllowToChangeBranch,
        string AllowBAtchEditable, string AllowBAtchEditablePAssword, string FIFOBasedBatchInventory,
        string AllowBackdateReqWOBOM, long MaxDurationForReqToBePend, string IssueWithScanner,
        string AllowBackDateRequsitionWITHBOM, string VendJWIssuePrintReportName, string VendJWRecPrintReportName,
        string AllowBackDateJOBWorkIssue,string ALLOWBACKDATEJobworkRec,string vendorJWAdjustAutoOrManual,
        string AllowBackDateStockAdjustment,string AllowBackDateInterStoreTransfer, string AllowBackdateIssueWOBOM,
        string AllowBackDateISSUEWITHBOM, string IssueViaScanningBarcode,string AllowBackDateIssueChallan,string ALLOWBACKDATRECCHALLAN,
        string RGPChallanPrintReportName,string NRGPChallanPrintReportName,string AllowBackDateReceiveChallanEntry,
        string CustJWIssuePrintReportName, string CUSTJWRecPrintReportName, string AllowBackDateCustomerJWIssue,
        string SaleBillPrintReportName,string JWSaleBillPrintReportName,string PurchaseRejPrintReportName,string DebitNotePrintReportName,
        string CreditNotePrintReportName,string SaleRejectionPrintReportName,string PurchaseBillPrintReportName,string DirectPurchaseBillPrintReportName,
        string PurchBillVoucherPrintReportName,string DirectPurchBillVoucherPrintReportName,string BankRecVoucherPrintReportName,
        string BankPaymentVoucherPrintReportName,string CashRecVoucherPrintReportName,string CashPaymentVoucherPrintReportName,
        string JournalVoucherPrintReportName, string PrdProdEntryAgainstWOProdSchReqManual,string AllowProdWithoutBom,
        string ProdSchAllowToAddManualNewItem,string ProdEntryAllowToAddRMItem,string ProdEntryAllowToAddWithoutRM,
        string ProdEntryAllowToAddNegativeStock,string BatchWiseProduction,string ProdEntryAllowBackDate,string AllowBackDateDAILYPRODUCTION,
        string AllowBackDateTRANSFERMATERIAL,string AllowBackDateRECEIVEINSTORE,string AllowBackDateSALEBILL,
        string VoucherRotationDailyMonthYearly, string AllowBackDateWorkorderEntry,string AllowBackDateProductionScheduleEntry,
        string InProdScheduleShowSumOrDetail,string PoallowtoprintWithoutApproval,
        string AccAllowtochangeDocumentinPurchaseBill,
string AccPasswordToChangeDocumentinPurchaseBill,
string AccAllowtochangeInvoiceNoDateinPurchaseBill,
string AccPasswordToAllowManualTax,
string AccSaleBillManualTaxAllowed,
string AccAllowBackdateVoucherEntry,
string AccBackdateVoucherEntryPassword,
string AccAllowToChangeVoucherDateInPurchBill,
string AccPurchaseVoucherPrintoutFilename,
string AccPurchaseBillInvoicePrintoutFilename)
        {
            _logger.LogInformation("\n \n ********** Page Features_Options ********** \n \n " + _IWebHostEnvironment.EnvironmentName.ToString() + "\n \n");

            // Clear TempData and set session variables
            TempData.Clear();
            var MainModel = new Features_OptionsModel();
            if (!string.IsNullOrEmpty(Mode) && ID > 0 && Mode == "U")
            {
                 MainModel = await _IFeatures_Options.GetViewByID( Type).ConfigureAwait(false);

                MainModel.Mode = Mode;
                MainModel.ID = ID;
                MainModel.Type = Type;
                MainModel.AutoGen_PartCode = AutoGen_PartCode;
                MainModel.DuplicateItemName = DuplicateItemName;
                MainModel.ItemPartcodeGenerationFormat = ItemPartcodeGenerationFormat;
                MainModel.Po_File_Name = Po_File_Name;
                MainModel.PONOEditable = PONOEditable;
                MainModel.PONOYearlyRenew = PONOYearlyRenew;
                MainModel.AutoGeneratedPUrchaseOrder = AutoGeneratedPUrchaseOrder;
                MainModel.PurchaseOrderReport = PurchaseOrderReport;
                MainModel.PurchaseorderPrintReportName = PurchaseorderPrintReportName;
                MainModel.PurchaseorderAmendPrintReportName = PurchaseorderAmendPrintReportName;
                MainModel.PurchasSchedulePrintReportName = PurchasSchedulePrintReportName;
                MainModel.PurchasScheduleAmendPrintReportName = PurchasScheduleAmendPrintReportName;
                MainModel.AllowBackDatePURCHASEORDER = AllowBackDatePURCHASEORDER;
                MainModel.AllowBackDateINDENT = AllowBackDateINDENT;
                MainModel.CheckPOPendFromPOonlyNotFromAmendment = CheckPOPendFromPOonlyNotFromAmendment;
                MainModel.SaleInvoiceFileName = SOFileName;
                MainModel.AutoGenItemGroupCode = AutoGenItemGroupCode;
                MainModel.AllowMultipleBuyerInSaleOrder = AllowMultipleBuyerInSO;
                MainModel.SaleorderPrintReportName = SOPrintReportName;
                MainModel.SaleAmendPrintReportName = SaleAmendPrintReportName;
                MainModel.SaleSchedulePrintReportName = SaleSchedulePrintReportName;
                MainModel.SaleScheduleAmendPrintReportName = SaleScheduleAmendPrintReportName;
                MainModel.BlockGateEntry4UnAppPOAmm = BlockGateEntry4UnAppPOAmm;
                MainModel.AllowBackDateGAteEntry = AllowBackDateGateEntry;
                MainModel.ShowRateINGAteMrn = ShowRateInGateMRN;
                MainModel.GateEntryPrintReportName = GateEntryPrintReportName;
                MainModel.AllowGateRateEnabled = AllowGateRateEnabled;
                MainModel.AllowBackDateMRNEntry = AllowBackDateMRNEntry;
                MainModel.AllowToChangeStoreInMRN = AllowToChangeStoreInMRN;
                MainModel.MRNPrintReportName = MRNPrintReportName;
                MainModel.AllowBackDateMRIR = AllowBackDateMRIR;
                MainModel.CCMandatoryInQuery = CCMandatoryInQuery;
                MainModel.BatchWiseInventory = BatchWiseInventory;
                MainModel.AllowToChangeBranch = AllowToChangeBranch;
                MainModel.AllowBAtchEditable = AllowBAtchEditable;
                MainModel.AllowBAtchEditablePAssword = AllowBAtchEditablePAssword;
                MainModel.FIFOBasedBatchInventory = FIFOBasedBatchInventory;
                MainModel.AllowBackdateReqWOBOM = AllowBackdateReqWOBOM;
                MainModel.MaxDurationForReqToBePend = MaxDurationForReqToBePend;
                MainModel.IssueWithScanner = IssueWithScanner;
                MainModel.AllowBackDateRequsitionWITHBOM = AllowBackDateRequsitionWITHBOM;
                MainModel.VendJWIssuePrintReportName = VendJWIssuePrintReportName;
                MainModel.VendJWRecPrintReportName = VendJWRecPrintReportName;
                MainModel.AllowBackDateJOBWorkIssue = AllowBackDateJOBWorkIssue;
                MainModel.ALLOWBACKDATEJobworkRec = ALLOWBACKDATEJobworkRec;
                MainModel.VendorJWAdjustAutoOrManual = vendorJWAdjustAutoOrManual;
                MainModel.AllowBackDateStockAdjustment = AllowBackDateStockAdjustment;
                MainModel.AllowBackDateInterStoreTransfer = AllowBackDateInterStoreTransfer;
                MainModel.AllowBackdateIssueWOBOM = AllowBackdateIssueWOBOM;
                MainModel.AllowBackDateISSUEWITHBOM = AllowBackDateISSUEWITHBOM;
                MainModel.IssueViaScanningBarcode = IssueViaScanningBarcode;
                MainModel.AllowBackDateIssueChallan = AllowBackDateIssueChallan;
                MainModel.ALLOWBACKDATRECCHALLAN = ALLOWBACKDATRECCHALLAN;
                MainModel.RGPChallanPrintReportName = RGPChallanPrintReportName;
                MainModel.NRGPChallanPrintReportName = NRGPChallanPrintReportName;
                MainModel.AllowBackDateReceiveChallanEntry = AllowBackDateReceiveChallanEntry;
                MainModel.CustJWIssuePrintReportName = CustJWIssuePrintReportName;
                MainModel.CUSTJWRecPrintReportName = CUSTJWRecPrintReportName;
                MainModel.AllowBackDateCustomerJWIssue = AllowBackDateCustomerJWIssue;
                MainModel.SaleBillPrintReportName = SaleBillPrintReportName;
                MainModel.JWSaleBillPrintReportName = JWSaleBillPrintReportName;
                MainModel.PurchaseRejPrintReportName = PurchaseRejPrintReportName;
                MainModel.DebitNotePrintReportName = DebitNotePrintReportName;
                MainModel.CreditNotePrintReportName = CreditNotePrintReportName;
                MainModel.SaleRejectionPrintReportName = SaleRejectionPrintReportName;
                MainModel.PurchaseBillPrintReportName = PurchaseBillPrintReportName;
                MainModel.DirectPurchaseBillPrintReportName = DirectPurchaseBillPrintReportName;
                MainModel.PurchBillVoucherPrintReportName = PurchBillVoucherPrintReportName;
                MainModel.DirectPurchBillVoucherPrintReportName = DirectPurchBillVoucherPrintReportName;
                MainModel.BankRecVoucherPrintReportName = BankRecVoucherPrintReportName;
                MainModel.BankPaymentVoucherPrintReportName = BankPaymentVoucherPrintReportName;
                MainModel.CashRecVoucherPrintReportName = CashRecVoucherPrintReportName;
                MainModel.CashPaymentVoucherPrintReportName = CashPaymentVoucherPrintReportName;
                MainModel.JournalVoucherPrintReportName = JournalVoucherPrintReportName;
                MainModel.PrdProdEntryAgainstWOProdSchReqManual = PrdProdEntryAgainstWOProdSchReqManual;
                MainModel.AllowProdWithoutBom = AllowProdWithoutBom;
                MainModel.ProdSchAllowToAddManualNewItem = ProdSchAllowToAddManualNewItem;
                MainModel.ProdEntryAllowToAddRMItem = ProdEntryAllowToAddRMItem;
                MainModel.ProdEntryAllowToAddWithoutRM = ProdEntryAllowToAddWithoutRM;
                MainModel.ProdEntryAllowToAddNegativeStock = ProdEntryAllowToAddNegativeStock;
                MainModel.BatchWiseProduction = BatchWiseProduction;
                MainModel.ProdEntryAllowBackDate = ProdEntryAllowBackDate;
                MainModel.AllowBackDateDAILYPRODUCTION = AllowBackDateDAILYPRODUCTION;
                MainModel.AllowBackDateTRANSFERMATERIAL = AllowBackDateTRANSFERMATERIAL;
                MainModel.AllowBackDateRECEIVEINSTORE = AllowBackDateRECEIVEINSTORE;
                MainModel.AllowBackDateSALEBILL = AllowBackDateSALEBILL;
                MainModel.VoucherRotationDailyMonthYearly = VoucherRotationDailyMonthYearly;
                MainModel.AllowBackDateWorkorderEntry = AllowBackDateWorkorderEntry;
                MainModel.AllowBackDateProductionScheduleEntry = AllowBackDateProductionScheduleEntry;
                MainModel.InProdScheduleShowSumOrDetail = InProdScheduleShowSumOrDetail;
                MainModel.PoallowtoprintWithoutApproval = PoallowtoprintWithoutApproval;

                MainModel.AccAllowtochangeDocumentinPurchaseBill = AccAllowtochangeDocumentinPurchaseBill;
                MainModel.AccPasswordToChangeDocumentinPurchaseBill = AccPasswordToChangeDocumentinPurchaseBill;
                MainModel.AccAllowtochangeInvoiceNoDateinPurchaseBill = AccAllowtochangeInvoiceNoDateinPurchaseBill;
                MainModel.AccPasswordToAllowManualTax = AccPasswordToAllowManualTax;
                MainModel.AccSaleBillManualTaxAllowed = AccSaleBillManualTaxAllowed;
                MainModel.AccAllowBackdateVoucherEntry = AccAllowBackdateVoucherEntry;
                MainModel.AccBackdateVoucherEntryPassword = AccBackdateVoucherEntryPassword;
                MainModel.AccAllowToChangeVoucherDateInPurchBill = AccAllowToChangeVoucherDateInPurchBill;
                MainModel.AccPurchaseVoucherPrintoutFilename = AccPurchaseVoucherPrintoutFilename;
                MainModel.AccPurchaseBillInvoicePrintoutFilename = AccPurchaseBillInvoicePrintoutFilename;





                if (Mode == "U")
                {
                    //MainModel.UpdatedByEmp = Convert.ToInt32(HttpContext.Session.GetString("UID"));
                    //MainModel.LastUpdatedBy = HttpContext.Session.GetString("EmpName");
                    //MainModel.UpdationDate = DateTime.Now.ToString();


                }
                MemoryCacheEntryOptions cacheEntryOptions = new MemoryCacheEntryOptions
                {
                    AbsoluteExpiration = DateTime.Now.AddMinutes(60),
                    SlidingExpiration = TimeSpan.FromMinutes(55),
                    Size = 1024
                };

            }
            else
            {
                // MainModel = await BindModels(MainModel);
            }

            return View(MainModel); 
        }
        [HttpPost]
        [Route("{controller}/Index")]
        public async Task<IActionResult> Features_Options(Features_OptionsModel model,string Type)
        {
            try
            {
                model.CreatedBy = Convert.ToInt32(HttpContext.Session.GetString("UID"));
                Type=model.Type;

                var Result = await _IFeatures_Options.SaveFeatures_Options(model);
                if (Result != null)
                {
                    if (Result.StatusText == "Success" && Result.StatusCode == HttpStatusCode.OK)
                    {
                        ViewBag.isSuccess = true;
                        TempData["200"] = "200";
                        _MemoryCache.Remove("CompanyGrid");
                    }
                    else if (Result.StatusText == "Success" && Result.StatusCode == HttpStatusCode.Accepted)
                    {
                        ViewBag.isSuccess = true;
                        TempData["202"] = "202";
                    }
                    else if (Result.StatusText == "Error" && Result.StatusCode == HttpStatusCode.InternalServerError)
                    {
                        ViewBag.isSuccess = false;
                        TempData["500"] = "500";
                        _logger.LogError($"\n \n ********** LogError ********** \n {JsonConvert.SerializeObject(Result)}\n \n");
                        return View("Error", Result);
                    }
                }

                return RedirectToAction(nameof(Features_OptionsDashBoard));

            }
            catch (Exception ex)
            {
                // Log and return the error
                LogException<Features_OptionsController>.WriteException(_logger, ex);
                var ResponseResult = new ResponseResult
                {
                    StatusCode = HttpStatusCode.InternalServerError,
                    StatusText = "Error",
                    Result = ex
                };
                return View("Error", ResponseResult);
            }
        }
        [HttpGet]
        public async Task<IActionResult> Features_OptionsDashBoard()
        {
            try
            {
                var model = new Features_OptionsModel();
                var result = await _IFeatures_Options.GetDashboardData( ).ConfigureAwait(true);
                DateTime now = DateTime.Now;

                //model.FromDate = new DateTime(now.Year, now.Month, 1).ToString("dd/MM/yyyy");
                //model.ToDate = new DateTime(now.Year + 1, 3, 31).ToString("dd/MM/yyyy");


                return View(model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public async Task<IActionResult> GetDetailData(string Type)
        {
            //model.Mode = "Search";
            var model = new Features_OptionsModel();
            model = await _IFeatures_Options.GetDashboardDetailData(Type);
            //return PartialView("_Features_OptionsItemDetail", model);
            if (Type == "ItemDetail")
            {
                return PartialView("_Features_OptionsItemDetail", model);
            }
            if (Type == "PurchaseDetail")
            {
                return PartialView("_Features_OptionsPurchaseDetail", model);
            }
            if (Type == "SaleOrderDetail")
            {
                return PartialView("_Features_OptionsSaleOrderDetail", model);
            }
             if (Type == "GateEntryDetail")
             {
                return PartialView("_Features_OptionsGateEntryDetail", model);
             }
                if (Type == "MRNDetail")
            {
                return PartialView("_Features_OptionsMRNDetail", model);
            }
            if (Type == "CommonDetail")
            {
                return PartialView("_Features_OptionsCommonDetail", model);
            }
             if (Type == "RequisitionDetail")
             {
                return PartialView("_Features_OptionsRequisitionDetail", model);
             }
             if (Type == "VendJwIssRecDetail")
             {
                return PartialView("_Features_OptionsVendJwIssRecDetail", model);
             }
             if (Type == "StockAdjDetail")
             {
                return PartialView("_Features_OptionsStockAdjDetail", model);
             }
             if (Type == "IssWithBomDetail")
             {
                return PartialView("_Features_OptionsIssWithBomDetail", model);
             }
              if (Type == "IssRecChallanDetail")
              {
                 return PartialView("_Features_OptionsIssRecChallanDetail", model);
              }
              if (Type == "JustJobWorkDetail")
              {
                 return PartialView("_Features_OptionsCustJobWorkDetail", model);
              }
              if (Type == "PrintReportDetail")
              {
                 return PartialView("_Features_OptionsPrintReportDetail", model);
              }
              if (Type == "ProdEntryDetail")
              {
                 return PartialView("_Features_OptionsProdEntryDetail", model);
              }
              if (Type == "ProdPlanSchDetail")
              {
                 return PartialView("Features_OptionsProdPlanSchDetail", model);
              }
              if (Type == "TransMtrFromWcRec")
              {
                 return PartialView("_Features_OptionsTransferWcRecDetail", model);
              }
              if (Type == "SaleBillDetail")
              {
                 return PartialView("_Features_OptionsSaleBillDetail", model);
              }
              if (Type == "AccountDetail")
              {
                 return PartialView("_Features_OptionsAccountDetail", model);
              }
               
            return null;
        }
    }
}
